# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0e8af92cd52a0b5fbb16163339ed5058"
application_url = "https://cio-response-unless-sufficiently.trycloudflare.com"
embedded = true
name = "flagship-interview"
handle = "flagship-interview"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "betbetterbusiness.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "orders/edited", "orders/updated" ]
  uri = "/webhooks/app/orders"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://cio-response-unless-sufficiently.trycloudflare.com/auth/callback",
  "https://cio-response-unless-sufficiently.trycloudflare.com/auth/shopify/callback",
  "https://cio-response-unless-sufficiently.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
